---
title: "esm206_lab7_KS"
author: "Katelin Seeto"
date: "11/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

### Attach packages and install effsize, and kableExtra

```{r}
install.packages("effsize")
install.packages("kableExtra")

library(tidyverse)
library(here)
library(janitor)
library(effsize)
library(kableExtra)

```


## Read in and explore Flint water data

```{r}
flint_pb <- read_csv("flint_water.csv") %>% 
  clean_names() %>% 
  rename(pb_immediate = pb_bottle_1_ppb_first_draw, 
         pb_2min = pb_bottle_2_ppb_2_mins_flushing) 
```

## Visually explore data

```{r}
# Histograms:
ggplot(flint_pb, aes(x = pb_immediate)) +
  geom_histogram()

ggplot(flint_pb, aes(x= pb_2min)) +
  geom_histogram()

# QQ Plot 
ggplot(flint_pb, aes(sample = pb_immediate)) +
  geom_qq()

ggplot(flint_pb, aes(sample = pb_2min)) +
  geom_qq()

# They are NOT normally distributed; we'll still say we want to compare means, and can do that comfortably because of CLT (sampling distribution of the means will be normal).
```

We should also look at some statistics for comparison: 

```{r}
# Sample size (non-NA):
n_immediate <- sum(!is.na(flint_pb$pb_immediate))
n_flushed <- sum(!is.na(flint_pb$pb_2min))

# Means (immediate v. 2 min flushing):
mean_immediate <- mean(flint_pb$pb_immediate, na.rm = TRUE)
mean_flushed <- mean(flint_pb$pb_2min, na.rm = TRUE)

# Medians (immediate v. 2 min flushing):
median_immediate <- median(flint_pb$pb_immediate, na.rm = TRUE)
median_flushed <- median(flint_pb$pb_2min, na.rm = TRUE)

# Standard deviations (immediate v. 2 min flushing):
sd_immediate <- sd(flint_pb$pb_immediate, na.rm = TRUE)
sd_flushed <- sd(flint_pb$pb_2min, na.rm = TRUE)

# Lead concentrations measured in immediately collected samples are much higher than those in water collected after 2 min flushing. 
```

#### Two-sample, two-sided **paired** t-test:

```{r}
my_flint_test <- t.test(flint_pb$pb_immediate, flint_pb$pb_2min, paired = TRUE)
```


